image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 11.19.0-debian-11-r2

auth:
  ## @param auth.enablePostgresUser Assign a password to the "postgres" admin user. Otherwise, remote access will be blocked for this user
  ##
  enablePostgresUser: true
  ## @param auth.postgresPassword Password for the "postgres" admin user. Ignored if `auth.existingSecret` with key `postgres-password` is provided
  ##
  postgresPassword: password
  ## @param auth.username Name for a custom user to create
  ##
  username: konga
  ## @param auth.password Password for the custom user to create. Ignored if `auth.existingSecret` with key `password` is provided
  ##
  password: konga
  ## @param auth.database Name for a custom database to create
  ##
  database: konga
