apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: sample-customization
upstream:
  hash_on: header
  hash_on_header: x-model-id
  hash_fallback: ip
  algorithm: consistent-hashing